# Generated by Django 2.2.5 on 2019-09-16 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='boy',
        ),
    ]
